### ISSUE TITLE
Makefile improvements

### ISSUE THREAD

**Issue by PVince81** [noveens/js-owncloud-client#23]
- Add a rule `deps` that pulls dependencies. All other rules like "test" must depend on it to make sure deps are installed.
- Extend the `clean` rule to also delete "node_modules". This way when you run `make clean` everything is back like a clean git clone.

**Comment by noveens** [comment]
Done : https://github.com/noveens/js-owncloud-client/commit/0792ba5176e2cc47e8959e797deed0256d4e39da
