### ISSUE TITLE
Keep namespaces in file info responses

### ISSUE THREAD

**Issue by PVince81** [noveens/js-owncloud-client#24]
`make swagger`
`curl -X GET "http://localhost:8080/list?depth=0" -H  "accept: application/json"`

Response is:
```
[
  {
    "name": "/",
    "type": "dir",
    "fileInfo": {
      "getlastmodified": "Wed, 21 Jun 2017 11:32:22 GMT",
      "resourcetype": {
        "d:collection": {}
      },
      "quota-used-bytes": "163",
      "quota-available-bytes": "-3",
      "getetag": "\"594a59463c67c\""
    }
  }
]
```

Considering that the file info response comes from XML, we need to keep the namespaces in case of naming collisions. I suggest using the Clark notation:
```json
    "fileInfo": {
      "{DAV:}getlastmodified": "Wed, 21 Jun 2017 11:32:22 GMT",
      "{DAV:}resourcetype": {
        "{DAV:}collection": {}
      },
      "{DAV:}quota-used-bytes": "163",
      "{DAV:}quota-available-bytes": "-3",
      "{DAV:}getetag": "\"594a59463c67c\"",
      "{http://owncloud.org/ns}fileid"
    }
```

**Comment by PVince81** [comment]
@noveens I think you had a PR already ?

**Comment by noveens** [comment]
@PVince81 ,
I don't know much about DAV namespaces, hence I kept this issue open to see if there was anything else required for this.

**Comment by PVince81** [comment]
They are actually XML namespaces, not DAV namespaces. Basically just the name of the attributes.

You could try reading a bit about XML namespaces in general.

I'm a bit surprised that this here works: https://github.com/noveens/js-owncloud-client/blob/master/owncloud/fileInfo.js#L68

I'd expect that when you keep the namespaces, it would change to something like `this.fileInfo['{DAV:}getcontentlength]`

**Comment by noveens** [comment]
@PVince81 ,
In my responses, I get something like: `{d:}getcontentlength` and not `{DAV:}getcontentlength`.
Views?

**Comment by PVince81** [comment]
This is probably because the XML parser or the method you use from the parser is giving you the namespace alias. You need to resolve the alias back to the original namespace name. Please check the parser functions, there is likely one to get the actual namespace name.

The reason for this is that you can never predict the alias. It is not guaranteed that the DAV alias will always be "d:". The reason it's "d" is only because the Sabre server implementation decided to use this letter as alias. I saw cases where it was just "a:", "b:", "c:" depending on the order.

I expect that a user of your API would use the full namespace name, not alias, when accessing custom properties.

**Comment by noveens** [comment]
Cool, I'll have a look into it.

**Comment by noveens** [comment]
@PVince81 ,

I'm having response like this directly from my OC instance like these:
```xml
<?xml version="1.0"?> 
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
    <d:response>
        <d:href>/core/remote.php/webdav/</d:href>
        <d:propstat>
            <d:prop>
                <d:getlastmodified>Mon, 26 Jun 2017 08:57:43 GMT</d:getlastmodified>               
                <d:resourcetype><d:collection/></d:resourcetype>
                <d:quota-used-bytes>3</d:quota-used-bytes>
                <d:quota-available-bytes>-3</d:quota-available-bytes>
                <d:getetag>&quot;5950cc87e601e&quot;</d:getetag>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>
```

**Comment by PVince81** [comment]
@noveens yes and no. The parser you are using should already have a function to get the namespace, you shouldn't do anything manually but rely on the library. The reason is that XML also allows to specify "xmlns" on individual element instead of the root element.
